// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NaviatePage.Models.Data;

public partial class Food
{
    public int Foodid { get; set; }

    public string Displayname { get; set; }

    public decimal Price { get; set; }

    public decimal? Discount { get; set; }

    public string Imagepath { get; set; }
}