// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NaviatePage.Models.Data;

public partial class Inputinfo
{
    public string Idinputinfo { get; set; }

    public string Idmaterial { get; set; }

    public string Idinput { get; set; }

    public int? Count { get; set; }

    public double? Inputprice { get; set; }

    public double? Outputprice { get; set; }

    public string Status { get; set; }

    public virtual Input IdinputNavigation { get; set; }

    public virtual Material IdmaterialNavigation { get; set; }
}