// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NaviatePage.Models.Data;

public partial class Input
{
    public string Idinput { get; set; }

    public DateTime? Dateinput { get; set; }

    public virtual ICollection<Inputinfo> Inputinfos { get; set; } = new List<Inputinfo>();
}