// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NaviatePage.Models.Data;

public partial class Output
{
    public string Idoutput { get; set; }

    public DateTime? Dateoutput { get; set; }

    public virtual ICollection<Outputinfo> Outputinfos { get; set; } = new List<Outputinfo>();
}