// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NaviatePage.Models.Data;

public partial class Supplier
{
    public int Idsupplier { get; set; }

    public string Displayname { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Moreinfo { get; set; }

    public DateTime? Contractdate { get; set; }

    public virtual ICollection<Material> Materials { get; set; } = new List<Material>();
}