// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NaviatePage.Models.Data;

public partial class Unit
{
    public int Idunit { get; set; }

    public string Displayname { get; set; }

    public virtual ICollection<Material> Materials { get; set; } = new List<Material>();
}