// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NaviatePage.Models.Data;

public partial class Userrole
{
    public int Iduserrole { get; set; }

    public string Displayname { get; set; }

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}