// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NaviatePage.Models.Data;

public partial class User
{
    public int Iduser { get; set; }

    public string Displayname { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }
    public string Email { get; set; }
    public int Iduserrole { get; set; }

    public virtual Userrole IduserroleNavigation { get; set; }
}